repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: check-docstring-first
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: requirements-txt-fixer

# CPPCheck is a useful static linter for detecting bugs.
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: cppcheck
        args: [--language=c++]

# CPPLint is useful for checking code styling and conventions.
-   repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
    -   id: cpplint
        files: '.ino'
        args: [--root=src]

# Project Code formatter for CPP source.
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
    -   id: clang-format
        args: ["--style=Google"]

# Hooks to verify Arduino Library conventions
-   repo: https://github.com/CreatingNull/arduino-hooks
    # Note for the pre-commit GitHub workflow this executable must be added.
    rev: v0.3.0
    hooks:
    -   id: arduino-lint
        args: [--fail-on-warn]
    -   id: arduino-cli
        args: ["--fqbn=arduino:avr:nano"]
        alias: "arduino-cli-nano"
        name: "arduino-cli-nano"
    -   id: arduino-cli
        args: [ "--fqbn=arduino:avr:uno" ]
        alias: "arduino-cli-uno"
        name: "arduino-cli-uno"
    -   id: arduino-cli
        args: ["--fqbn=rp2040:rp2040:rpipico"]
        alias: "arduino-cli-rpipico"
        name: "arduino-cli-rpipico"
