repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: requirements-txt-fixer
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: cppcheck
        args: [--language=c++]
-   repo: https://github.com/cpplint/cpplint
    rev: 1.5.5
    hooks:
    -   id: cpplint
        files: '.ino'
        args: [--root=src]
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
    -   id: clang-format
        args: [-i, --style=Google]
-   repo: https://github.com/CreatingNull/arduino-hooks
    # Note for the pre-commit GitHub workflow this executable must be added.
    rev: v0.1.0
    hooks:
    -   id: arduino-lint
        args: [--fail-on-warn]
