name: pre-commit

on:

  pull_request:
  push:
    branches:
      - main

jobs:

  pre-commit:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2

    - name: Install System Dependancies
      run: |
        pip install --upgrade pip wheel
        sudo apt-get update -y
        sudo apt-get install -y cppcheck
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | sh -s 1.2.0
        echo "${PWD}/bin/" >> $GITHUB_PATH
    - name: Run Pre-Commit
      uses: pre-commit/action@v2.0.3
